apply plugin: 'com.android.application'
def VERSION_CODE = 1
def VERSION_NAME = "1.0.1"
def keystoreFilepath = ''
def keyfile = file('s.keystore.temp')

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())
keystoreFilepath = properties.getProperty("keystore.path")

if (keystoreFilepath) {
    keyfile = file(keystoreFilepath)
}

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        applicationId "com.haohai.haohai.address"
        minSdkVersion 19
        targetSdkVersion rootProject.targetSdkVersion
        versionCode VERSION_CODE
        versionName VERSION_NAME
        multiDexEnabled true

       /* testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"*/
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }


        signingConfigs {
            config {
                keyAlias 'haohai'
                keyPassword 'haohaiadmin'
                storeFile file('C:/workspaces/HuiYanWeiXing/app/sign.jks')
                storePassword 'haohaiadmin'
            }
        }
        buildTypes {
            debug {
                println("====== buildTypes.debug ======")
                signingConfig signingConfigs.debug
            }
            release {
                //是否混淆
                minifyEnabled false
                //是否移除无用资源
                zipAlignEnabled true
                //混淆配置
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                //签名文件存在，则签名
                if (keyfile.exists()) {
                    println("WITH -> buildTypes -> release: using jks key")
                    signingConfig signingConfigs.config
                } else {
                    println("WITH -> buildTypes -> release: using default key")
                }
                applicationVariants.all { variant ->
                    variant.outputs.each { output ->
                        def outputFile = output.outputFile
                        if (outputFile != null && outputFile.name.endsWith('.apk')) {
                            // 输出apk名称为ruijie_v1.0_wandoujia.apk
                            def fileName = "address_v${defaultConfig.versionName}_${variant.productFlavors[0].name}.apk"
                            output.outputFile = new File(outputFile.parent, fileName)
                        }
                    }
                }
                signingConfig signingConfigs.config
            }
        }
        lintOptions {
            abortOnError false
        }

        android {
            productFlavors {
                /*  kuan {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "kuan"]
                }*/
                xiaomi {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "xiaomi"]
                }
                /*   qh360 {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "qh360"]
                }
                baidu {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "baidu"]
                }
                wandoujia {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "wandoujia"]
                }
                oppo {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "oppo"]
                }
                vivo {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "vivo"]
                }
                huawei {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "huawei"]
                }
                yingyongbao {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "yingyongbao"]
                }
                anzhi {
                    manifestPlaceholders = [UMENG_CHANNEL_VALUE: "anzhi"]
                }*/
            }
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

//将so库打包到apk中
    sourceSets {
        main {
            jniLibs.srcDir 'libs'
            jni.srcDirs = []
        }
    }

    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
   /* compileOptions{
        sourceCompatibility org.gradle.api.JavaVersion.VERSION_1_8
        targetCompatibility org.gradle.api.JavaVersion.VERSION_1_8
    }*/
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile project(':hhlibrary')

  /*  compile 'com.esri.arcgisruntime:arcgis-android:100.6.0'*/
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.google.code.gson:gson:2.6.2'
}
