apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

def VERSION_CODE = 14
def VERSION_NAME = "1.2.4"
def keystoreFilepath = ''
def keyfile = file('s.keystore.temp')

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())
keystoreFilepath = properties.getProperty("keystore.path")

if (keystoreFilepath) {
    keyfile = file(keystoreFilepath)
}

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.3'

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }

    defaultConfig {
        applicationId "com.skyline.terraexplorer"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode VERSION_CODE
        versionName VERSION_NAME
        multiDexEnabled true
        ndk {
            //根据需要 自行选择添加的对应cpu类型的.so库。
            abiFilters 'armeabi', 'armeabi-v7a'
            // 还可以添加 'x86', 'x86_64', 'mips', 'mips64'
        }
        manifestPlaceholders = [
                JPUSH_PKGNAME: "com.skyline.terraexplorer",
                JPUSH_APPKEY : "c156f37c8c84543573a7aef9", //JPush 上注册的包名对应的 Appkey.
                JPUSH_CHANNEL: "developer-default", //暂时填写默认值即可.
        ]

        signingConfigs {
            config {
                keyAlias 'haohai'
                keyPassword 'haohaiadmin'
                storeFile file('.../sign.jks')
                //storeFile file('C:/workspaces/HuiYanWeiXing/app/sign.jks')
                storePassword 'haohaiadmin'
            }
        }

        buildTypes {
            debug {
                println("====== buildTypes.debug ======")
                signingConfig signingConfigs.debug
            }

            release {
                //是否混淆
                minifyEnabled false
                //是否移除无用资源
                zipAlignEnabled true
                //混淆配置
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                //签名文件存在，则签名
                if (keyfile.exists()) {
                    println("WITH -> buildTypes -> release: using jks key")
                    signingConfig signingConfigs.config
                } else {
                    println("WITH -> buildTypes -> release: using default key")
                }
                applicationVariants.all { variant ->
                    variant.outputs.each { output ->
                        def outputFile = output.outputFile
                        if (outputFile != null && outputFile.name.endsWith('.apk')) {
                            /* def fileName = "haohai_v${defaultConfig.versionName}_${variant.productFlavors[0].name}.apk"*/
                            /*   def fileName = "qd_wgh${defaultConfig.versionName}.apk"*/
                            def fileName = "qd_wgh${defaultConfig.versionName}.apk"
                            output.outputFile = new File(outputFile.parent, fileName)
                        }
                    }
                }
                signingConfig signingConfigs.config
            }
        }

        lintOptions {
            abortOnError false
        }


        productFlavors {
            /*  kuan {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "kuan"]
            }*/
            xiaomi {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "xiaomi"]
            }
            /*   qh360 {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "qh360"]
            }
            baidu {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "baidu"]
            }
            wandoujia {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "wandoujia"]
            }
            oppo {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "oppo"]
            }
            vivo {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "vivo"]
            }
            huawei {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "huawei"]
            }
            yingyongbao {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "yingyongbao"]
            }
            anzhi {
                manifestPlaceholders = [UMENG_CHANNEL_VALUE: "anzhi"]
            }*/
        }

    }



    sourceSets {
        main {
            proto {
                srcDir 'src/main/proto'
                include '**/*.proto'
            }
            java {
                srcDir 'src/main/java'
            }


        }
    }




    useLibrary 'org.apache.http.legacy'

    dexOptions {
        javaMaxHeapSize "4g"
    }

    lintOptions {
        abortOnError false
    }
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }


}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/commons-jexl-2.1.1.jar')
    compile files('libs/tileviewlib-1.0.11.jar')
    compile files('libs/poi-3.15.jar')
    compile files('libs/sdlv.jar')
    compile files('libs/netty-all-4.0.56.Final.jar')
    compile files('libs/poi-scratchpad-3.15.jar')
    compile('com.zhihu.android:matisse:0.4.3', {
        exclude group: 'com.android.support'
    })
    //compile 'com.android.support:recyclerview-v7:26.0.1'
    /*compile project(':hhlibrary')*/
    compile('me.drakeet.multitype:multitype:2.2.2', {
        exclude group: 'com.android.support'
    })

    // compile 'ch.ielse:imagewatcher:1.0.3'
    compile('ch.ielse:imagewatcher:1.0.3', {
        exclude group: 'com.android.support'
    })

    //compile 'com.android.support:recyclerview-v7:23.+'

    /*    compile 'com.squareup.okhttp3:okhttp:3.14.2'
    compile 'com.squareup.okio:okio:1.17.4'*/
    compile 'cn.jiguang.sdk:jpush:3.3.4'
    compile 'cn.jiguang.sdk:jcore:2.1.2'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.2.0'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.android.support:support-v4:26.0.0-alpha1'
    compile 'com.github.vilyever:AndroidSocketClient:3.0.3'
    compile 'com.google.protobuf:protobuf-java:3.1.0'
    compile 'com.google.protobuf:protoc:3.1.0'
    compile 'de.hdodenhof:circleimageview:2.2.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.blankj:utilcode:1.16.0'
    compile 'com.zhy:okhttputils:2.6.2'
    compile 'com.github.franmontiel:PersistentCookieJar:v1.0.1'
    compile 'com.github.clans:fab:1.6.4'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'org.xutils:xutils:3.3.36'
    compile 'io.reactivex.rxjava2:rxjava:2.0.5'
    compile 'io.reactivex:rxandroid:1.2.0'
    compile 'com.jakewharton.rxbinding:rxbinding:0.4.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.1@aar'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.android.support:recyclerview-v7:26.0.0-alpha1'
    compile 'com.liulishuo.filedownloader:library:1.7.7'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.1.0'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
            }
            task.builtins {
                java {}
                cpp {}
            }
        }
    }
    generatedFilesBaseDir = "$projectDir/src/generated"
}