apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

def keyfile = file('s.keystore.temp')
def keystoreFilepath = ''

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())
keystoreFilepath = properties.getProperty("keystore.path")

if (keystoreFilepath) {
    keyfile = file(keystoreFilepath)
}


android {
    compileSdkVersion 29
    buildToolsVersion "30.0.3"
    useLibrary "org.apache.http.legacy"

    defaultConfig {
        applicationId "com.skyline.terraexplorer"
        minSdkVersion 26
        targetSdkVersion 29
        versionCode 11
        versionName "1.1.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        packagingOptions {
            //解决编译时com.android.builder.merge.DuplicateRelativeFileException: More than one file was found with OS independent path 'META-INF/rxjava.properties'这个错误
            exclude 'META-INF/rxjava.properties'
        }

        manifestPlaceholders = [
                JPUSH_PKGNAME: "com.skyline.terraexplorer",
                JPUSH_APPKEY : "c156f37c8c84543573a7aef9", //JPush 上注册的包名对应的 Appkey.
                JPUSH_CHANNEL: "developer-default", //暂时填写默认值即可.
                XG_ACCESS_ID : "1500040370",
                XG_ACCESS_KEY : "ASK8CFJD7L2D",
                //HW_APPID: "103450845"
        ]

        multiDexEnabled true
        ndk {
            //根据需要 自行选择添加的对应cpu类型的.so库。
            abiFilters 'armeabi','armeabi-v7a'
            // 还可以添加 'x86', 'x86_64', 'mips', 'mips64'
        }
    }

    signingConfigs {
        config {
            keyAlias 'key0'
            keyPassword '123456'
            storeFile file('../app/signs.jks')
            //storeFile file('C:/workspaces/haohai/FireForestPlatform/app/signs.jks')
            storePassword '123456'
        }
    }



    buildTypes {
        debug {
            println("====== buildTypes.debug ======")
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.config
            //是否混淆
            minifyEnabled false
            shrinkResources false
            ndk{
                abiFilters "armeabi-v7a"
            }
        }
    }
//    dataBinding {
//        enabled = true
//    }

    lintOptions {
        abortOnError false
    }
    buildFeatures{
        dataBinding = true
        // for view binding :
        // viewBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    flavorDimensions "app"
    productFlavors {
        /*  xiaomi {
              manifestPlaceholders = [UMENG_CHANNEL_VALUE: "xiaomi"]
          }*/
        /*  kuan {
            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "kuan"]
        }*/
        xiaomi {
            dimension 'app'
            manifestPlaceholders = [
                    UMENG_CHANNEL_VALUE: "xiaomi",
            ]
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation files('libs/commons-jexl-2.1.1.jar')
    implementation files('libs/tileviewlib-1.0.11.jar')
    implementation files('libs/AMap3DMap_7.1.0_AMapNavi_7.1.0_20191030.jar')
    implementation files('libs/poi-3.15.jar')
    implementation files('libs/sdlv.jar')
    implementation files('libs/netty-all-4.0.56.Final.jar')
    implementation files('libs/poi-scratchpad-3.15.jar')
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation project(path: ':hhlibrary')
    implementation files('libs/AMap3DMap_7.1.0_AMapNavi_7.1.0_20191030.jar')
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.github.f0ris.sweetalert:library:1.5.1'
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
    implementation 'com.github.AlpsDog:Banner:v1.0.6'
    implementation 'com.jakewharton.rxbinding:rxbinding:0.4.0'
//    implementation 'com.github.wendux:DSBridge-Android:3.0.0'
    implementation 'com.amap.api:location:5.5.1'
    implementation 'com.google.code.gson:gson:2.8.8'
    implementation 'org.xutils:xutils:3.3.36'
    implementation ('me.drakeet.multitype:multitype:3.5.0', {
        exclude group: 'com.android.support'
    })
    implementation 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.1@aar'
    implementation 'io.reactivex.rxjava2:rxjava:2.0.1'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.0.0'
    implementation('com.zhihu.android:matisse:0.4.3', {
        exclude group: 'com.android.support'
    })
    implementation 'com.zhy:okhttputils:2.6.2'
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    implementation 'com.squareup.okhttp3:okhttp:3.14.1'
    implementation 'org.apache.httpcomponents:httpclient-android:4.3.5'

    //WisdomGarden
//    implementation 'com.github.wendux:DSBridge-Android:3.0-SNAPSHOT'
    implementation project(path: ':dsbridge')
    implementation 'com.rxjava.rxhttp:rxhttp:1.1.6'
    implementation 'com.github.RmondJone:LockTableView:1.1.2'
    annotationProcessor 'com.rxjava.rxhttp:rxhttp-compiler:1.1.6'


    //qd-grid-app
    implementation 'cn.jiguang.sdk:jpush:3.3.4'
    implementation 'cn.jiguang.sdk:jcore:2.1.2'
    implementation('ch.ielse:imagewatcher:1.0.3', {
        exclude group: 'com.android.support'
    })
    implementation 'com.github.vilyever:AndroidSocketClient:3.0.3'
    implementation 'com.google.protobuf:protobuf-java:3.1.0'
    implementation 'com.google.protobuf:protoc:3.1.0'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.github.franmontiel:PersistentCookieJar:v1.0.1'
    implementation 'com.blankj:utilcode:1.16.0'
    implementation 'com.github.clans:fab:1.6.4'
    implementation 'com.liulishuo.filedownloader:library:1.7.7'

//    implementation 'commons-logging:commons-logging:1.2'
    api 'com.github.chrisbanes:PhotoView:2.0.0'


    implementation 'com.tencent.jg:jg:1.1'     //腾讯推送
    implementation 'com.tencent.tpns:tpns:1.2.0.3-release' //腾讯推送

    implementation project(':hhlibrary')
    implementation project(':videolibrary')

    implementation 'org.greenrobot:eventbus:3.1.1'
}


protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.1.0'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
            }
            task.builtins {
                java {}
                cpp {}
            }
        }
    }
    generatedFilesBaseDir = "$projectDir/src/generated"
}